version: '3'

services:
  api:
    build:
      context: .
    networks:
      - traefik-net
    labels:
      - "traefik.http.routers.songs-api.rule=Host(`songs.localhost`)"
      - "traefik.http.services.songs-api.loadbalancer.server.port=1234"

networks:
  traefik-net:
    external: true